(function ensightenInit(){var ensightenOptions = {client: "hearst", clientId: 109, publishPath: "mag", bootstrapVersion: "v13", isPublic:0, serverComponentLocation: "nexus.ensighten.com/hearst/mag/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/hearst/mag/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Thu Mar 19 12:33:36 GMT 2026", beaconSamplingSeedValue: 11, dataLayerName: "ensDataLayer"};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(l){function r(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+" is missing"}function t(a){this.name="BeaconException";this.message="There was an error during beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function w(){for(var a=e.dataDefinitionIds.length,b=!0,d=0;d<a;d++){var f=e.dataDefinitions[e.dataDefinitionIds[d]];if(!f||
null==f.endRegistration){b=!1;break}}b&&e.callOnDataDefintionComplete()}var c={},e={};e.ensightenOptions=ensightenOptions;e.scDataObj={};var A="",x=null;if(document.currentScript&&document.currentScript.src){var q=document.currentScript.src;/^[A-Za-z][A-Za-z0-9+.-]*:/.test(q)||(q.startsWith("//")||(q="//"+q),q=window.location.protocol+q);q=new URL(q);A=q.hostname;q=q.pathname;q.startsWith(`/${ensightenOptions.client}/${ensightenOptions.publishPath}/sha`)&&(x=q.split("/"),x=x[x.length-2]||null)}c.version=
"1.26.0";c.getDynamicDomain=function(){if(A)return A;for(var a=null,b=document.getElementsByTagName("script"),d=l.client+"/"+l.publishPath+"/Bootstrap.js",f=l.client+"/Bootstrap.js",h=0;h<b.length;h++)if(-1<b[h].src.indexOf(d)||"prod"==l.publishPath&&-1<b[h].src.indexOf(f)){a=b[h];break}return a?(b=document.createElement("a"),b.href=a.getAttribute("src"),b.hostname):""};ensightenOptions.nexus=c.nexus=ensightenOptions.nexus||c.getDynamicDomain()||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();
c.options={interval:l.interval||100,erLoc:l.errorLocation||c.nexus+"/error/e.gif",scLoc:l.serverComponentLocation||c.nexus+"/"+l.client+"/serverComponent.php",sjPath:l.staticJavascriptPath||c.nexus+"/"+l.client+"/code/",alLoc:l.alertLocation||c.nexus+"/alerts/a.gif",publishPath:l.publishPath,isPublic:l.isPublic,client:l.client,clientId:l.clientId,enableTagAuditBeacon:l.enableTagAuditBeacon,beaconSamplingSeedValue:l.beaconSamplingSeedValue||-1,dataLayerName:l.dataLayerName||"ensDataLayer",protocol:"http:"===
window.location.protocol?window.location.protocol:"https:",sriPath:x};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.appIdWhitelist=[];c.appIdBlacklist=[];window[c.options.dataLayerName]&&window[c.options.dataLayerName][0]&&(window[c.options.dataLayerName][0]["ens.whitelist"]&&(c.appIdWhitelist=window[c.options.dataLayerName][0]["ens.whitelist"]),window[c.options.dataLayerName][0]["ens.blacklist"]&&(c.appIdBlacklist=window[c.options.dataLayerName][0]["ens.blacklist"]));
c.canRuleRunByAppId=function(a){return a?a&&!a.appId||a&&-1==a.appId||0==c.appIdWhitelist.length&&0==c.appIdBlacklist.length?!0:0<c.appIdWhitelist.length&&0==c.appIdBlacklist.length?-1==c.appIdWhitelist.indexOf(a.appId)?!1:!0:0==c.appIdWhitelist.length&&0<c.appIdBlacklist.length?-1==c.appIdBlacklist.indexOf(a.appId)?!0:!1:0<c.appIdWhitelist.length&&0<c.appIdBlacklist.length&&-1==c.appIdBlacklist.indexOf(a.appId)&&-1!=c.appIdWhitelist.indexOf(a.appId)?!0:!1:!1};c.test=function(a){if(c.canRuleRunByAppId(a)&&
!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;a.execute()}};r.prototype=Error();r.prototype||(r.prototype={});r.prototype.constructor=r;c.DependencyNotAvailableException=r;t.prototype=Error();t.prototype||(t.prototype={});t.prototype.constructor=t;c.BeaconException=t;c.checkForInvalidDependencies=function(a,b,d,f){for(var h=0;h<d.length;h++)if("DEPENDENCYNEVERAVAILABLE"===d[h])return e.currentRuleId=
a,e.currentDeploymentId=b,e.reportException(new c.DependencyNotAvailableException(f[h])),b&&-1!==b&&c.allDeploymentIds.push(b),!0;return!1};e.currentRuleId=-1;e.currentDeploymentId=-1;e.reportedErrors=[];e.reportedAlerts=[];e.AF=[];c.initialized=!1;e.extend=function(a){c.initialized&&window[ensightenOptions.ns].reportException({name:"CoreExtendException",message:"Core extend was called after initialization"})};e.initialize=function(){c.initialized||(this.extend(c),c.initialized=!0)};e.sampleBeacon=
function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(f){}return a};e.getServerComponent=function(a){e.callOnGetServerComponent();var b=c.options.protocol+"//"+("/"==c.options.scLoc.charAt(0)?c.getDynamicDomain():"")+c.options.scLoc;c.options.sriPath&&(b=b.replace("/serverComponent.php",`/${c.options.sriPath}/serverComponent.php`));a=c.constructScUrl(b,a||!0);fetch(a).then(d=>d.ok?d.json():(window[ensightenOptions.ns].reportException({name:"getServerComponentException",
message:"Network response was not ok"}),{})).then(d=>{c.process(d)}).catch(d=>{window[ensightenOptions.ns].reportException({name:"getServerComponentException",message:"There was a problem with the fetch operation:"+d})})};c.constructScUrl=function(a,b){b=1==b&&"object"==typeof e.scDataObj?e.scDataObj:b;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));var d=window.location.href;if("object"===typeof b)for(i in b&&b.PageID&&(d=b.PageID,delete b.PageID),b){var f=~d.indexOf("#")?d.slice(d.indexOf("#"),
d.length):"";d=d.slice(0,f.length?d.length-f.length:d.length);d+=~d.indexOf("?")?"&":"?";for(k in b)d+=k+"="+b[k]+"&";d=d.slice(0,-1)+f;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";return a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(d)+("/"==c.options.scLoc.charAt(0)?"&custDomain="+c.getDynamicDomain():"")};c.process=function(a){a.pageFiles&&Array.isArray(a.pageFiles)&&0<a.pageFiles.length&&e.insertPageFiles(a.pageFiles);
a.dataDefinitionIds&&Array.isArray(a.dataDefinitionIds)&&0<a.dataDefinitionIds.length&&e.setPageSpecificDataDefinitionIds(a.dataDefinitionIds);a.context&&(e.context=a.context)};e.setVariable=function(a,b){c.ensightenVariables[a]=b};e.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};e.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a]);c.testAndGroups()};e.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,
readyForServerComponent:!1};e.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=c.options.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(a.rid||e.currentRuleId||
-1)+"&did="+encodeURIComponent(a.did||e.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=e.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a);e.currentRuleId=-1;e.currentDeploymentId=-1};e.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);e.currentRuleId=this.id;e.currentDeploymentId=this.deploymentId;try{this.code()}catch(b){window[ensightenOptions.ns].reportException(b)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&
(c.runDeploymentIds.push(this.deploymentId),c.runRuleIds.push(this.id)),e.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.appId=a.appId;this.executionData={hasRun:!1,runTime:[]}};c.updateRuleEvent=function(a,b){for(var d=0;d<c.ruleList.length;d++)if(null!=c.ruleList[d].eventTriggerObj&&c.ruleList[d].eventTriggerObj.rid==a)return c.ruleList[d].id=a,c.ruleList[d].deploymentId=b,c.ruleList[d].executionData.hasRun=!0,c.ruleList[d].executionData.runTime=
[new Date],c.allDeploymentIds.push(b),c.runDeploymentIds.push(b),c.runRuleIds.push(a),!0;return!1};e.triggerEvent=function(a,b){const d=e.getRule(a);d&&d.executionData.hasRun||(d?c.setHasRun(d,a,b):c.updateRuleEvent(a,b)||window[ensightenOptions.ns].reportException({rid:a,did:b,name:"triggerEvent error",message:"rid not found in rule.eventTriggerObj in registered rule list. Dependent Tag can not run due to missing event object."}))};c.setHasRun=function(a,b,d){a.executionData.hasRun||(a.executionData.hasRun=
!0,a.executionData.runTime=[new Date],c.runDeploymentIds.push(d),c.runRuleIds.push(b))};e.registerRule=function(a){if(e.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);e.testAll();return!0};e.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};e.getRuleList=function(){return c.ruleList};e.clearRuleList=function(){c.ruleList=[];c.andGroups={}};e.getAllDeploymentIds=function(){return c.allDeploymentIds};
e.getRunRuleIds=function(){return c.runRuleIds};e.getRunDeploymentIds=function(){return c.runDeploymentIds};e.hasRuleRun=function(a){return e.checkHasRun([a])};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};e.Alert=function(a){var b=new Date;b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||
1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};e.generateAlert=function(a){a=e.imageRequest(c.options.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+e.currentRuleId+"&did="+e.currentDeploymentId);a.timestamp=(new Date).getTime();
this.reportedAlerts.push(a)};e.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};e.insertScript=function(a,b,d,f){var h=document.getElementsByTagName("script"),g;if(void 0!==b?b:1)for(g=0;g<h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(!f)var m=d;else if(d){d=1==d&&"object"==typeof e.scDataObj?e.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));b=window.location.href;"object"===typeof d&&d.PageID&&(b=d.PageID,delete d.PageID);
if("object"===typeof d)for(g in d){g=~b.indexOf("#")?b.slice(b.indexOf("#"),b.length):"";b=b.slice(0,g.length?b.length-g.length:b.length);b+=~b.indexOf("?")?"&":"?";for(k in d)b+=k+"="+d[k]+"&";b=b.slice(0,-1)+g;break}a=a+"?namespace="+(ensightenOptions.ns+"&");a+="staticJsPath="+ensightenOptions.staticJavascriptPath+"&";a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(b)+("/"==c.options.scLoc.charAt(0)?"&custDomain="+c.getDynamicDomain():"")}(function(p,n,v){var u=
n.head||n.getElementsByTagName("head"),B=function(){if("item"in u){if(!u[0]){setTimeout(B,25);return}u=u[0]}var y=n.createElement("script"),z;for(z in m)y.setAttribute(z,m[z]?m[z]:null);v&&(y.src=v);y.onload=y.onerror=function(){this.addEventListener&&(this.readyState="loaded")};u.insertBefore(y,u.firstChild)};setTimeout(B,0)})(window,document,a,m)};e.loadScriptCallback=function(a,b,d,f,h){var g=document.getElementsByTagName("script"),m=g[0];h=h||!1;if(d)for(d=0;d<g.length;d++)if(g[d].src===a&&g[d].readyState&&
/loaded|complete/.test(g[d].readyState))try{b()}catch(n){window[ensightenOptions.ns].reportException(n)}finally{return}g=document.createElement("script");for(var p in f)g.setAttribute(p,f[p]?f[p]:null);g.type="text/javascript";g.async=!0;g.src=a;g.onerror=function(){this.addEventListener&&(this.readyState="loaded")};g.onload=g.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&
(this.readyState="loaded");try{b.call(this)}catch(n){window[ensightenOptions.ns].reportException(n)}}};h?(a=document.head||document.getElementsByTagName("head")[0],a.insertBefore(g,a.firstChild)):m.parentNode.insertBefore(g,m)};e.insertPageFiles=function(a){var b=0,d=0,f=function(){d==a.length-1&&window[ensightenOptions.ns].callOnPageSpecificCompletion();d++};for(b=0;b<a.length;++b)if("string"===typeof a[b])window[ensightenOptions.ns].loadScriptCallback(a[b],f);else{const {src:h,integrity:g}=a[b];
window[ensightenOptions.ns].loadScriptCallback(h,f,!1,g?{integrity:g,crossorigin:"anonymous"}:{},!0)}};e.unobtrusiveAddEvent=function(a,b,d){try{var f=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return f.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};e.anonymous=function(a,b){return function(){try{e.currentRuleId=b?b:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};e.setCurrentRuleId=function(a){e.currentRuleId=a};e.setCurrentDeploymentId=
function(a){e.currentDeploymentId=a};c.bind=function(a,b,d,f,h,g){if("function"===typeof a)a=new e.Rule({id:b||-1,deploymentId:d||-1,appId:f||-1,dependencies:"immediate"==h?[]:[function(){return window[ensightenOptions.ns].executionState[h]}],code:a}),null!=g&&(a.eventTriggerObj=g);else if("object"!==typeof a)return!1;e.registerRule(a)};e.bindImmediate=function(a,b,d,f){c.bind(a,b,d,f,"immediate")};e.bindDOMParsed=function(a,b,d,f){c.bind(a,b,d,f,"DOMParsed")};e.bindDOMLoaded=function(a,b,d,f){c.bind(a,
b,d,f,"DOMLoaded")};e.bindPageSpecificCompletion=function(a,b,d,f){c.bind(a,b,d,f,"conditionalRules")};e.bindOnGetServerComponent=function(a,b,d,f){c.bind(a,b,d,f,"readyForServerComponent")};e.bindDataDefinitionComplete=function(a,b,d,f){c.bind(a,b,d,f,"dataDefinitionComplete")};e.checkHasRun=function(a){return 0===a.length?!0:a.every(b=>c.runRuleIds.includes(b))};c.bindDependency=function(a,b,d,f,h,g,m,p){var n=[];if(!c.checkForInvalidDependencies(b,f,d,h)){"immediate"==!m&&n.push(function(){return window[ensightenOptions.ns].executionState[m]});
n.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new e.Rule({id:b||-1,deploymentId:f||-1,appId:g||-1,dependencies:n,code:a}),null!=p&&(a.eventTriggerObj=p);else if("object"!==typeof a)return!1;e.registerRule(a)}};e.bindDependencyImmediate=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"immediate")};e.bindDependencyDOMLoaded=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"DOMLoaded")};e.bindDependencyDOMParsed=function(a,b,d,f,h,g){c.bindDependency(a,
b,d,f,h,g,"DOMParsed")};e.bindDependencyPageSpecificCompletion=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"conditionalRules")};e.bindDependencyOnGetServerComponent=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"readyForServerComponent")};e.bindDependencyDataDefinitionComplete=function(a,b,d,f,h,g){c.bindDependency(a,b,d,f,h,g,"dataDefinitionComplete")};e.dataDefinitionIds=[];e.dataDefinitions=[];e.pageSpecificDataDefinitionsSet=!1;e.setPageSpecificDataDefinitionIds=function(a){for(var b=
a?a.length:0,d=0;d<b;d++){var f=a[d];if(Array.prototype.indexOf)-1==e.dataDefinitionIds.indexOf(f)&&e.dataDefinitionIds.push(f);else{for(var h=!1,g=e.dataDefinitionIds.length,m=0;m<g;m++)if(e.dataDefinitionIds[m]===f){h=!0;break}h||e.dataDefinitionIds.push(f)}}e.pageSpecificDataDefinitionsSet=!0;w()};e.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=
function(){this.endRegistrationTime=new Date}};e.registerDataDefinition=function(a,b){var d=e.dataDefinitions[b];d||(d=new e.DataDefinition(b,a),e.dataDefinitions[b]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());e.pageSpecificDataDefinitionsSet&&w()};e.callOnDataDefintionComplete=function(){e.executionState.dataDefinitionComplete=!0;e.testAll()};e.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};
e.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};e.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=
!0;window[ensightenOptions.ns].testAll()},1)};e.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};e.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};e.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};e.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};c.andGroups={};c.testAndGroups=
function(){Object.keys(c.andGroups).forEach(function(a){const b=c.andGroups[a];b.eventNames?b.eventNames.every(function(d){return 0<b.triggeredEvents[d].length})&&(b.ddConditions?c.testDataDefsAndExecute(b):c.executeGroup(b)):b.hasRun||b.rule.executionData.hasRun||(b.ddConditions?c.testDataDefsAndExecute(b):c.executeGroup(b))})};c.testDataDefsAndExecute=function(a){e.executionState.dataDefinitionComplete&&!a.resolving&&(a.resolving=!0,e.data.resolve(a.ddConditions.requiredData,function(){a.resolving=
!1;a.ddConditions.values=Array.prototype.slice.call(arguments,0);e.data.checkConditions(a.ddConditions)&&c.executeGroup(a)},!0))};c.__no_op=function(){};c.__false=function(){return!1};c.registerAndGroup=function(a,b,d,f,h,g,m,p){f=null==f||0===f.length?null:f;const n=c.generateGroupId(a,b,f,g);if(!(c.andGroups[n]||m&&c.checkForInvalidDependencies(a,b,m,p))){var v=e.getRule(a);!f&&v&&v.executionData.hasRun||(v||(v=new e.Rule({id:a,deploymentId:b,appId:d,code:c.__no_op,dependencies:[c.__false]}),e.registerRule(v)),
c.andGroups[n]={eventNames:f,triggeredOrder:new Set,triggeredEvents:{},callback:h,ddConditions:g,rid:a,did:b,dependencyRids:m,dependencyDids:p,rule:v,hasRun:!1},f&&f.forEach(function(u){c.andGroups[n].triggeredEvents[u]=[];window[ensightenOptions.ns].ensEvent.add(u,function(){c.storeTriggeredEvent(n,u,this!==window?this:null)})}))}};c.storeTriggeredEvent=function(a,b,d){if(a=c.andGroups[a])a.triggeredOrder.add(b),a.triggeredEvents[b].push({data:d,timestamp:(new Date).getTime()})};c._boxedPrimitives=
["[object Number]","[object String]","[object Boolean]","[object Symbol]"];c.isObject=function(a){a=a.data;if(null===a||"object"!==typeof a)return!1;a=Object.prototype.toString.call(a);return!c._boxedPrimitives.includes(a)};c.executeGroup=function(a){if(a.eventNames||!a.hasRun&&!a.rule.executionData.hasRun){var b=a.eventNames?a.eventNames.every(function(f){return 0<a.triggeredEvents[f].length}):!0,d=a.dependencyRids?e.checkHasRun(a.dependencyRids):!0;if(b&&d){b=a.eventNames?Array.from(a.triggeredOrder).map(function(f){return{name:f,
...a.triggeredEvents[f].splice(0,a.triggeredEvents[f].length).pop()}}):[];a.triggeredOrder.clear();d=b.filter(f=>c.isObject(f)).length===b.length;d=0===b.length?null:1!==b.length&&d?b.reduce((f,h)=>({...f,...h.data}),{}):b[b.length-1].data;try{a.callback.call(d,b),a.hasRun=!0,c.setHasRun(a.rule,a.rid,a.did)}catch(f){e.reportException(f)}}}};c.generateGroupId=function(a,b,d,f){return`and_${a}_${b}_${d?d.join("_"):""}_${f?f.requiredData.join("_"):""}`};e.bindAndGroup=function(a,b,d,f,h,g,m,p,n){c.bind(function(){c.registerAndGroup(d,
f,h,g,a,m,p,n)},-1,-1,h,b)};e.getAndGroups=function(){return c.andGroups};var C=function(){var a=[],b=!1,d=!1;return{add:function(f){b&&!d?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){d=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);d=!1},haveRun:function(){return b}}};e.new_fArray=function(){return C()};c.timer=null;(function(){function a(f,h){return function(){f.apply(h,arguments)}}
window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var d=log4javascript.getDefaultLogger();b.log=a(d.info,d);b.debug=a(d.debug,d);b.info=a(d.info,d);b.warn=a(d.warn,d);b.error=a(d.error,d)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&
(clearInterval(c.timer),e.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",e.callOnDOMParsed,!1),window.addEventListener("load",e.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document,b=function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(d){setTimeout(b,15);return}window[ensightenOptions.ns].callOnDOMParsed()};b()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===
document.readyState&&(e.executionState.DOMParsed=!0,e.executionState.DOMLoaded=!0);"true"===c.options.enableTagAuditBeacon&&e.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],b,d,f,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],f=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+f,a.push(h);b="["+a.join(";")+"]";var m=c.options.protocol+"//"+c.nexus+"/"+encodeURIComponent(l.client)+
"/"+encodeURIComponent(l.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(l.clientId)+"&data="+b+"&idx=0&r="+c.rand;e.imageRequest(m)}catch(p){e.currentRuleId=-1,e.currentDeploymentId=-1,a=new c.BeaconException(p),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(e.testAll,c.options.interval);return e}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var l=window.performance;if(l){l=l.timing||{};var r=l.navigationStart||0,t={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var w="&ns="+encodeURIComponent(l.navigationStart);for(var c in t)if(void 0!==l[c]){var e=l[c]-r;w+="&"+t[c]+"="+(0<e?encodeURIComponent(e):0)}else w+="&"+t[c]+"=-1";window[ensightenOptions.ns].timing=w;c=ensightenOptions.nexus||"nexus.ensighten.com";l=ensightenOptions.staticJavascriptPath||
"";w=l.indexOf("/",0);r=l.indexOf("/code/");l=l.substring(w,r)+"/perf.rnc";l+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+l)}}});

const _public=window[ensightenOptions.ns],extend=_public.extend;
_public.extend=function(b){extend(b);b.ruleEventList=[];b.hasObjectWithRuleIdAndEventName=function(c){return b.ruleEventList.some(function(a){return a.ruleId===c.ruleId&&a.eventName===c.eventName})};b.registerRuleEvent=function(c,a){var f=[];Array.isArray(a)&&a.forEach(function(e){var d={ruleId:c,eventName:e};b.hasObjectWithRuleIdAndEventName(d)||(f.push(e),b.ruleEventList.push(d))});return f};b.bindEvents=function(c,a,f,e,d,g){var h=b.registerRuleEvent(a,d);0<h.length&&(-1==a?b.bind(c,-1,-1,e,g):
b.bind(function(){window[ensightenOptions.ns].ensEvent.add(h,c)},-1,-1,e,g,{eventTrigger:!0,rid:a,did:f}))};_public.ensEvent=_public.ensEvent||{};_public.ensEvent.setRuleEventList=function(c){b.ruleEventList=JSON.parse(JSON.stringify(c))};_public.ensEvent.clearRuleEventList=function(){b.ruleEventList=[]};_public.ensEvent.getRuleEventList=function(){return b.ruleEventList};_public.bindEventImmediate=function(c,a,f,e,d){b.bindEvents(c,a,f,e,d,"immediate")};_public.bindEventDOMParsed=function(c,a,f,
e,d){b.bindEvents(c,a,f,e,d,"DOMParsed")};_public.bindEventDOMLoaded=function(c,a,f,e,d){b.bindEvents(c,a,f,e,d,"DOMLoaded")};b.bindEventDependency=function(c,a,f,e,d,g,h,l){var k=b.registerRuleEvent(a,l);0<k.length&&(-1==a?b.bindDependency(c,-1,d,-1,d,g,h):b.bindDependency(function(){window[ensightenOptions.ns].ensEvent.add(k,c)},-1,f,-1,d,g,h,{eventTrigger:!0,rid:a,did:e}))};_public.bindEventDependencyImmediate=function(c,a,f,e,d,g,h){b.bindEventDependency(c,a,f,e,d,g,"immediate",h)};_public.bindEventDependencyDOMLoaded=
function(c,a,f,e,d,g,h){b.bindEventDependency(c,a,f,e,d,g,"DOMLoaded",h)};_public.bindEventDependencyDOMParsed=function(c,a,f,e,d,g,h){b.bindEventDependency(c,a,f,e,d,g,"DOMParsed",h)}};
window[ensightenOptions.ns].initialize();
/*
 MIT License (c) copyright 2013 original author or authors */
window[ensightenOptions.ns].data||(window[ensightenOptions.ns].when=function(){function e(g,l,t,w){return v(g).then(l,t,w)}function B(g){this.then=g}function v(g){return f(function(l){l(g)})}function f(g){function l(A){C&&(x=d(A),b(C,x),C=y)}function t(A){l(h(A))}function w(A){C&&b(C,a(A))}var x,C=[];try{g(l,t,w)}catch(A){t(A)}return new B(function(A,F,G){return f(function(H,N,I){C?C.push(function(L){L.then(A,F,G).then(H,N,I)}):n(function(){x.then(A,F,G).then(H,N,I)})})})}function d(g){return g instanceof
B?g:g!==Object(g)?r(g):f(function(l,t,w){n(function(){try{var x=g.then;"function"===typeof x?T(x,g,l,t,w):l(r(g))}catch(C){t(C)}})})}function r(g){var l=new B(function(t){try{return"function"==typeof t?d(t(g)):l}catch(w){return h(w)}});return l}function h(g){var l=new B(function(t,w){try{return"function"==typeof w?d(w(g)):l}catch(x){return h(x)}});return l}function a(g){var l=new B(function(t,w,x){try{return"function"==typeof x?a(x(g)):l}catch(C){return a(C)}});return l}function b(g,l){n(function(){for(var t,
w=0;t=g[w++];)t(l)})}function c(g,l,t,w,x){q(2,arguments);return e(g,function(C){return f(function(A,F,G){function H(M){P(M)}function N(M){Q(M)}var I;var L=C.length>>>0;var O=Math.max(0,Math.min(l,L));var R=[];var W=L-O+1;var U=[];if(O){var P=function(M){U.push(M);--W||(Q=P=p,F(U))};var Q=function(M){R.push(M);--O||(Q=P=p,A(R))};for(I=0;I<L;++I)I in C&&e(C[I],N,H,G)}else A(R)}).then(t,w,x)})}function k(g,l,t,w){q(1,arguments);return u(g,z).then(l,t,w)}function u(g,l){return e(g,function(t){return f(function(w,
x,C){var A,F;var G=A=t.length>>>0;var H=[];if(G){var N=function(I,L){e(I,l).then(function(O){H[L]=O;--G||w(H)},x,C)};for(F=0;F<A;F++)F in t?N(t[F],F):--G}else w(H)})})}function n(g){1===E.push(g)&&K(m)}function m(){for(var g,l=0;g=E[l++];)g();E=[]}function q(g,l){for(var t,w=l.length;w>g;)if(t=l[--w],null!=t&&"function"!=typeof t)throw Error("arg "+w+" must be a function");}function p(){}function z(g){return g}e.defer=function(){var g,l;var t={promise:y,resolve:y,reject:y,notify:y,resolver:{resolve:y,
reject:y,notify:y}};t.promise=g=f(function(w,x,C){t.resolve=t.resolver.resolve=function(A){if(l)return v(A);l=!0;w(A);return g};t.reject=t.resolver.reject=function(A){if(l)return v(h(A));l=!0;x(A);return g};t.notify=t.resolver.notify=function(A){C(A);return A}});return t};e.resolve=v;e.reject=function(g){return e(g,h)};e.join=function(){return u(arguments,z)};e.all=k;e.map=u;e.reduce=function(g,l){var t=T(V,arguments,1);return e(g,function(w){var x=w.length;t[0]=function(C,A,F){return e(C,function(G){return e(A,
function(H){return l(G,H,F,x)})})};return X.apply(w,t)})};e.any=function(g,l,t,w){return c(g,1,function(x){return l?l(x[0]):x[0]},t,w)};e.some=c;e.isPromise=function(g){return g&&"function"===typeof g.then};B.prototype={otherwise:function(g){return this.then(y,g)},ensure:function(g){function l(){return v(g())}return this.then(l,l).yield(this)},yield:function(g){return this.then(function(){return g})},spread:function(g){return this.then(function(l){return k(l,function(t){return g.apply(y,t)})})},always:function(g,
l){return this.then(g,g,l)}};var y;var E=[];var D=setTimeout;var K="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(g){D(g,0)};var J=Function.prototype;var S=J.call;var T=J.bind?S.bind(S):function(g,l){return g.apply(l,V.call(arguments,2))};J=[];var V=J.slice;var X=J.reduce||function(g){var l=0;var t=Object(this);var w=t.length>>>0;var x=arguments;if(1>=x.length)for(;;){if(l in
t){x=t[l++];break}if(++l>=w)throw new TypeError;}else x=x[1];for(;l<w;++l)l in t&&(x=g(x,t[l],l,t));return x};return e}(),function(){function e(d,r){return v.all(r||[],function(h){return d.apply(null,h)})}function B(d){var r=f.call(arguments,1);return function(){return e(d,r.concat(f.call(arguments)))}}var v=window[ensightenOptions.ns].when;var f=[].slice;v.apply=e;v.call=function(d){return e(d,f.call(arguments,1))};v.lift=B;v.bind=B;v.compose=function(d){var r=f.call(arguments,1);return function(){var h=
f.call(arguments);h=e(d,h);return v.reduce(r,function(a,b){return b(a)},h)}}}(),window[ensightenOptions.ns].data=function(e,B){function v(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var f={engines:{memory:{get:function(a){if(d.utils.isArray(a)){for(var b=[],c=0;c<a.length;c++)b.push(f.data[a[c]]);return e[ensightenOptions.ns].when.resolve(b)}b=f.dataDefinitions[a]||{storage:{get:function(){}}};b=b.storage.get(b);f.data[a]=
b;return e[ensightenOptions.ns].when.resolve(f.data[a])},set:function(a,b){if(d.utils.isArray(a))for(var c in a)f.data[a[c]]=b[c];else f.data[a]=b;return e[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(d.utils.isArray(a))for(var b in a)delete f.data[a[b]];else delete f.data[a];return e[ensightenOptions.ns].when.resolve(!0)},clear:function(a){f.data={};f.definitions={};return e[ensightenOptions.ns].when.resolve(!0)},all:function(){return e[ensightenOptions.ns].when.resolve(f.data)}}},
normalizeInputArgs:function(a,b){var c={key:[],val:B},k;if(d.utils.isPlainObject(a))for(k in c.val=[],a)c.key.push(k),c.val.push(a[k]);else d.utils.isArray(a),c.key=a,c.val=b;return c},definitions:{},data:{}},d={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},r=function(){return e[ensightenOptions.ns].when.reject("Not Implemented.")};
v.prototype=Error();v.prototype||(v.prototype={});v.prototype.constructor=v;f.DataDefinitionException=v;f.checkForInvalidDataDefinitions=function(a){d.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a)),!0):!1};f.collectAvailableDataDefinitions=function(a){for(var b=[],c=0;c<a.length;c++){var k=parseInt(a[c],10),u=e[ensightenOptions.ns].dataDefinitions[k];if(null===u||u===B)if(u=d.storage.session.get({id:k}),
null!==u&&u!==B)d.set(k,u),f.dataDefinitions[k]={id:k,load:"visitor",storage:d.storage.visitor,missingDDFromCache:!0},b.push(e[ensightenOptions.ns].data.get(""+k));else return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Invalid data definition used: "+k)),{promises:[],isInvalid:!0};else b.push(e[ensightenOptions.ns].data.get(""+a[c]))}return{promises:b,isInvalid:!1}};f.getSync=function(a){function b(p){var z=p.extract||k,y=p.transform||u,E=!1,D=null,K=null;try{D=z()}catch(J){D=
null,E=!0}try{K=y(D)}catch(J){K=null,E=!0}E&&c.push(p.id);return K}var c=[],k=function(){return document},u=function(p){return null!==p&&p!==B?p.toString():null},n=parseInt(a);a="string"===typeof a?a.split("."):[];var m={},q="";if(!isNaN(n)&&"undefined"===typeof f.dataDefinitions[n])return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(n,"Error resolving data definition: "+n+".  Does not exist on the page.")),"Data definition specified does not exist on the page";if(isNaN(n)&&
"undefined"===typeof f.dataDefinitionsBySourceCollName[""+a[0]+"."+a[1]+"."+a[2]])return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definition: "+a[0]+"."+a[1]+"."+a[2]+".  Does not exist on the page.")),"Data definition specified does not exist on the page";isNaN(n)?3==a.length&&(m=d.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):m=d.getDataDefinitionById(n);q=m.load&&m.load.match(/(session|visitor)/i)&&m.storage&&m.storage.get?m.storage.get(m):
b(m);0<c.length&&e[ensightenOptions.ns].reportException(new f.DataDefinitionException(c,"Error resolving data definitions synchronously: "+c));return q};f.dataDefinitions={};f.dataDefinitionsBySourceCollName={};d.defineEngine=function(a,b){var c=["get","set","remove","clear","all"];f.engines[a]=b;if(!b.returnsPromise)for(a=0;a<c.length;a++){var k=c[a];b[k]=e[ensightenOptions.ns].when.lift(b[k])}};d.storage={instance:{set:function(a,b){},get:function(a){return f.getSync(a.id)}},page:{set:function(a,
b){},get:function(a){return f.data[a.id]}},session:{set:function(a,b){var c=d.storage.session.get({id:a}),k=new Date,u=k.getTime();k.setTime(u+18E5);null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:k.toGMTString()});b={expires:k.getTime(),value:b};e[ensightenOptions.ns].data.local.utils.set(a,b)},get:function(a){var b=e[ensightenOptions.ns].data.cookie.utils.get(a.id),c=e.JSON&&e.JSON.stringify?e.JSON:e[ensightenOptions.ns].JSON;c=c||{};var k=new Date;k=k.getTime();if(null===
b){try{var u=c.parse(e[ensightenOptions.ns].data.local.utils.get(a.id))}catch(n){u=null}null!=u&&(u.expires=+u.expires,k<=u.expires?b=u.value:""==u.expires&&u.value!=B?b=u.value:e[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},visitor:{set:function(a,b){var c=d.storage.session.get({id:a});null!=c&&(b=c);e[ensightenOptions.ns].data.cookie.utils.set(a,b);e[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return d.storage.session.get(a)}}};d.getEngine=
d.engine=function(a){return a?f.engines[a]||{get:r,set:r,remove:r,clear:r,all:r}:f.engines};d.all=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").all()};d.get=function(a,b,c){b=b||"memory";c=c||{};-1<a.indexOf(",")?(a=a.split(","),a=f.normalizeInputArgs(a)):a=f.normalizeInputArgs(a);return c.wait?f.getWait(a.key,e[ensightenOptions.ns].data.engine(b),c):f.data&&f.data.hasOwnProperty(a.key)?e[ensightenOptions.ns].data.engine(b).get(a.key):f.getWaitForKey(a.key,e[ensightenOptions.ns].data.engine(b),
c)};f.getWait=function(a,b,c){var k=+new Date,u=e[ensightenOptions.ns].when.defer(),n=function(){var q=b.get(a);if(-1===c.wait)return q;q.then(function(p){c.setCheck(p)?u.resolve(p):setTimeout(m,c.interval)},function(p){setTimeout(m,c.interval)})},m=function(){var q=+new Date-k;-1!==c.wait&&q<c.wait?n():u.reject("Timeout")};c.interval=c.interval||500;c.wait=c.wait||5E3;d.utils.isArray(a)?c.setCheck=c.setCheck||function(q){for(var p=!0,z=0;z<q.length;z++)p=p&&!!q[z];return p}:c.setCheck=c.setCheck||
function(q){return!!q};n();return u.promise};f.getWaitForKey=function(a,b,c){var k=e[ensightenOptions.ns].when.defer(),u=function(){if(f.data&&f.data.hasOwnProperty(a)){var m=b.get(a);if(-1===c.wait)return m;m.then(function(q){k.resolve(q)},function(q){k.reject(q)})}else setTimeout(n,c.interval)},n=function(){u()};c.interval=c.interval||100;c.wait=c.wait||1;u();return k.promise};d.set=function(a,b,c){var k=f.normalizeInputArgs(a,b);Array.prototype.slice.call(arguments);return e[ensightenOptions.ns].data.engine(c||
"memory").set(k.key,k.val)};d.remove=function(a,b){return e[ensightenOptions.ns].data.engine(b||"memory").remove(a)};d.clear=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").clear()};d.define=function(a,b){b&&(a.name=b.id||b.name);if(!a.name)return e[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;b=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return e[ensightenOptions.ns].when.resolve()};
a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=e[ensightenOptions.ns].data.engine("memory");a.storage=d.storage[b.toLowerCase()]||d.storage.page;a.resolved=!1;var c=a.extract||function(){return document},k=a.transform||function(q){return q},u=function(q,p){var z=[];z.push(a.persist.set(q,p));a.storage.set(a.id,p);"object"==typeof e[ensightenOptions.ns].data.dataExport&&e[ensightenOptions.ns].data.dataExport(q,p,a.collection);e[ensightenOptions.ns].when.all(z).then(function(y){n.resolve(y)},
function(y){n.reject(y)})},n=e[ensightenOptions.ns].when.defer();try{var m=a.trigger()}catch(q){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,'"'+q+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),m=e[ensightenOptions.ns].data.bottomOfBodyTrigger()}m.then(function(){var q=n,p=q.resolve,z=e[ensightenOptions.ns].when,y=z.reduce;try{var E=c()}catch(D){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,
'"'+D+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),E=null}p.call(q,y.call(z,[E,function(){try{return k.apply(this,arguments)}catch(D){return e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,'"'+D+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},u],function(D,K,J,S){a.resolved=!0;if(1==J)return K(D);2==J&&K(a.name,D)}))},function(q){n.reject(q)});f.dataDefinitions[a.id]=a;f.dataDefinitionsBySourceCollName[""+
a.source+"."+a.collection+"."+a.dataDefName]=a;return n.promise};d.checkConditions=function(a){var b,c={lt:function(n,m){var q=+n,p=+m;return isNaN(q)||isNaN(p)?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+n+", compareTo: "+m)),!1):q<p},gt:function(n,m){var q=+n,p=+m;return isNaN(q)||isNaN(p)?(e[ensightenOptions.ns].reportException(new f.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+
n+", compareTo: "+m)),!1):q>p},eql:function(n,m){return n==m},exists:function(n,m){return n===B?!1:!0},re:function(n,m,q){m=new RegExp(m,q?"i":"");try{return n.match(m)}catch(p){return!1}},starts:function(n,m,q){m=d.utils.escapeRegEx(m);return c.re(n,"^"+m,q)},ends:function(n,m,q){m=d.utils.escapeRegEx(m);return c.re(n,m+"$",q)},contains:function(n,m,q){m=d.utils.escapeRegEx(m);return c.re(n,".*"+m+".*",q)}};c.is=c.eql;c["starts with"]=c.starts;c["ends with"]=c.ends;c["is greater than"]=c.gt;c["is less than"]=
c.lt;c.matches=c.re;for(b=0;b<a.values.length;b++){var k=a.customComparator?a.customComparator[b]?a.customComparator[b]:c[a.comparators[b]]:c[a.comparators[b]],u=k(a.values[b],a.compareTo[b],a.caseInsensitive?a.caseInsensitive[b]||!1:!1);a.not[b]&&(u=!u);if(!u&&k!=c.exists)return!1}return!0};d.triggerPromise=function(a,b,c){c=c||5E3;var k=+new Date,u=e[ensightenOptions.ns].when.defer(),n=function(){var m=a();m!=b?u.resolve(m):+new Date-k<c?setTimeout(n,200):u.reject("timed out")};n();return u.promise};
d.timeoutPromise=function(a,b){var c=e[ensightenOptions.ns].when.defer();b=b||800;a.then(c.resolve,c.reject);setTimeout(function(){c.reject(Error("timed out"))},b);return c.promise};d.delayTrigger=function(a){a=a||10;var b=e[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},a);return b.promise};d.delayUntilTrigger=function(a,b,c,k){c=c||null;k=k||200;var u=+new Date,n=e[ensightenOptions.ns].when.defer(),m=function(){var q=a();q!=b?n.resolve(q):c?+new Date-u<c?setTimeout(m,k):n.reject("timed out"):
setTimeout(m,k)};m();return n.promise};f.applyTrigger=function(a){var b=e[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};d.immediateTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindImmediate)};d.bottomOfBodyTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindDOMParsed)};d.whenValueExistsTrigger=function(){return e[ensightenOptions.ns].when.resolve(this.extract())};d.afterEnsightenCompleteTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindPageSpecificCompletion)};
d.afterElementsDownloadedTrigger=function(){return f.applyTrigger(e[ensightenOptions.ns].bindDOMLoaded)};d.getAllDataDefinitionsOnCurrentPage=function(){return f.dataDefinitions};d.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return f.dataDefinitionsBySourceCollName};d.getDataDefinitionById=function(a){return f.dataDefinitions[a||-1]||{}};d.getDataDefinitionBySourceCollectionName=function(a,b,c){return f.dataDefinitionsBySourceCollName[""+a+"."+b+"."+c]||{}};d.getDataDefinitionByPercentSyntax=
function(a){a=(""+a).split("_");return 1>a.length?{}:f.dataDefinitions[a[1]]||{}};d.resolve=function(a,b,c){function k(){var q=f.collectAvailableDataDefinitions(a);q.isInvalid||e[ensightenOptions.ns].when.all(q.promises).then(function(p){try{b.apply(u,p)}catch(z){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+z))}},function(p){e[ensightenOptions.ns].reportException(new f.DataDefinitionException(a,"Error resolving data definitions: "+
a+". Details: "+p))})}var u=this,n=null;if(!f.checkForInvalidDataDefinitions(a))if(b){if(c)return k();e[ensightenOptions.ns].bindDataDefinitionComplete(k)}else{c=[];n=a;d.utils.isArray(a)||(n=[a]);for(var m=0;m<n.length;m++)c.push(f.getSync(n[m]));return n=d.utils.isArray(a)?c:c[0]}};d.extract=function(a,b){var c="",k=function(){for(var p={},z=e.document.getElementsByTagName("META")||[],y=0,E=z.length;y<E;y++){var D=z[y].name||z[y].getAttribute("property")||"";0!==D.length&&(p[D]=z[y].content)}return p}(),
u=function(p){var z=k[p];if(z)return z;z=e.document.getElementsByTagName("META")||[];for(var y=0,E=z.length;y<E;y++){var D=z[y].name||z[y].getAttribute("property")||"";if(p==D)return z[y].content}},n=function(p){return(val=(new RegExp("&"+p+"=([^&]*)")).exec(e.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},m=function(p){return(val=(new RegExp("^"+p+"=.*|;\\s*"+p+"=.*")).exec(e.document.cookie))?val[0].split("=")[1].split(";")[0]:""},q=function(p){(p=getElement(p))&&p.nodeType&&1==p.nodeType&&
(p=p.value||p.innerHTML||"");return p.toString().replace(/\n|\r|\s\s+/g,"")||""};try{return b?"meta"==b?c=u(a):"cookie"==b?c=m(a):"param"==b?c=n(a):"content"==b?c=q(a):"var"==b&&(c=e[a]):c=u(a)||m(a)||n(a)||q(a)||e[a]||"",c||""}catch(p){return""}};d.event_param={};if("undefined"==typeof h)var h={exports:{}};return d}(window),window[ensightenOptions.ns].data.defineEngine("store",function(){var e={},B=window,v,f=Array.isArray||function(h){return"[object Array]"===Object.prototype.toString.call(h)};
e.set=function(h,a){};e.get=function(h){};e.remove=function(h){};e.clear=function(){};try{if("localStorage"in B&&B.localStorage){var d=B.localStorage;e.set=function(h,a){var b,c=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(f(h)){var k=0;for(b=h.length;k<b;k++)d.setItem(h[k],"string"===typeof a[k]?a[k]:c.stringify(a[k]))}else d.setItem(h,"string"===typeof a?a:c.stringify(a))};e.get=function(h){if(f(h)){var a={},b;var c=0;for(b=h.length;c<b;c++)a[h[c]]=d.getItem(h[c]);
return a}return d.getItem(h)};e.remove=function(h){if(f(h)){var a;var b=0;for(a=h.length;b<a;b++)d.removeItem(h[b])}else d.removeItem(h)};e.clear=function(){d.clear()};e.all=function(){return d}}}catch(h){}var r={};for(v in e)r[v]=e[v];r.testStorage=function(){try{var h="tk_"+Math.ceil(5E7*Math.random());r.set(h,"test");if("test"===r.get(h))return r.remove(h),!0}catch(a){}return!1};e.utils=r;return window[ensightenOptions.ns].data.local=e}()),window[ensightenOptions.ns].data.defineEngine("cookie",
function(e,B){var v=function(){return v.get.apply(v,arguments)},f=v.utils={isArray:Array.isArray||function(d){return"[object Array]"===Object.prototype.toString.call(d)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(d){return Array.prototype.slice.call(d)},getKeys:Object.keys||function(d){var r=[],h="";for(h in d)d.hasOwnProperty(h)&&r.push(h);return r},escape:function(d){return String(d).replace(/[,;"\\=\s%]/g,function(r){return encodeURIComponent(r)})},retrieve:function(d,
r){return null==d?r:d},getAllCookies:function(){if(""===e.cookie)return{};for(var d=e.cookie.split("; "),r={},h=0,a=d.length;h<a;h++){var b=d[h].split("=");r[decodeURIComponent(b[0])]=decodeURIComponent(b[1])}return r},set:function(d,r,h){h=h||-1;if(f.isPlainObject(d))for(var a in d)d.hasOwnProperty(a)&&v.set(a,d[a],r);else if(f.isArray(d)){var b;a=0;for(b=d.length;a<b;a++)v.set(d[a],r[a],h)}else{a=h.expires!==B?h.expires:v.defaults.expires||"";"number"===typeof a&&(a=new Date(a));a=f.isPlainObject(a)&&
"toGMTString"in a?";expires="+a.toGMTString():f.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;b=(b=h.path||v.defaults.path)?";path="+b:"";var c=h.domain||v.defaults.domain;c=c?";domain="+c:"";h=h.secure||v.defaults.secure?";secure":"";e.cookie=f.escape(d)+"="+f.escape(r)+a+b+c+h}},get:function(d,r){r=r||B;var h=f.getAllCookies();if(f.isArray(d)){for(var a={},b=0,c=d.length;b<c;b++)a[d[b]]=f.retrieve(h[d[b]],r),a[d[b]]===B&&(a[d[b]]=null);return a}a=f.retrieve(h[d],
r);return a===B?null:a},getGMTString:function(d){var r=new Date;r.setTime(r.getTime()+864E5*d);return r.toGMTString()}};v.defaults={path:"/",expires:f.getGMTString(90)};v.set=function(d,r){f.set(d,r)};v.remove=function(d){d=f.isArray(d)?d:f.toArray(arguments);for(var r=0,h=d.length;r<h;r++)f.set(d[r],"",{expires:-1})};v.clear=function(){return v.remove(f.getKeys(f.getAllCookies()))};v.get=function(d,r){return f.get(d,r)};v.all=function(){return f.getAllCookies()};v.utils=f;return window[ensightenOptions.ns].data.cookie=
v}(document)));

const __public=window[ensightenOptions.ns];
if(!__public.ensEvent||!__public.ensEvent.defined){const t=function(k,l){var d={queue:{},pollQueue:{},max_recur:1E3,pushTrigger:function(a,b){if("[object Array]"===Object.prototype.toString.call(a)){for(var c=0;c<a.length;c++)d.pushTrigger(a[c],b);return!0}if("string"!=typeof a)return!1;this.queue[a]=this.queue[a]||{fn:[]};"function"==typeof b&&this.queue[a].fn.push(b);d.addEventRunTime("eventsAdded",a);return!0},callTrigger:function(a,b,c,p){if("string"!=typeof a)return!1;var e=d.queue[a];if("object"==
typeof e&&e.fn&&e.fn.length){if(0!=e.fireOnFirstSet&&c==l||c!=l&&0!=e.fireOnUpdate){const q={name:a,data:this!==k?this:null,timestamp:Date.now()};for(var f=b;f<e.fn.length;f++)try{e.fn[f].call(this,[q]),d.addEventRunTime("eventsTriggered",a)}catch(r){__public.reportException(r)}}e=e.fn.length;__public.testAll();d.queue[a].fn.length>e&&(b>=d.max_recur?__public.reportException({name:"EventTriggerRecursionLimitExceeded",message:"Event - "+a+" trigger reached the max recursion depth limit."}):d.callTrigger(a,
e,c,p))}},addEventRunTime:function(a,b){var c=__public.ensEvent;c[a]=c[a]||{};c[a][b]=c[a][b]||{runTimes:[]};c[a][b].runTimes.push((new Date).getTime())},clearQueue:function(){this.queue={}},getQueue:function(){return this.queue}};let m=!1;const g=[];__public.bindPageSpecificCompletion(function(){for(m=!0;0<g.length;){const a=g.shift();n.trigger(a.name,a.ref)}});let h=!1;var n={add:function(a,b){return d.pushTrigger(a,b)},get:function(a){return d.queue[a]},trigger:function(a,b){if(m)return b=b||k,
__public.data=__public.data||{},__public.data.event_param=b||{},d.callTrigger.call(b||Bootstrapper,a,0);g.push({name:a,ref:b})},initialize:function(){h||(this.extend(d),h=!0)},extend:function(a){h&&__public.reportException({name:"EventExtendException",message:"Event extend was called after event initialization."})},clearQueue:function(){d.clearQueue()},getQueue:function(){return d.getQueue()},defined:!0};return n}(window);Object.assign(__public.ensEvent,t)};

window[ensightenOptions.ns].ensEvent.initialize();
Bootstrapper.dataDefinitionIds = [56304,55204,60964];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){if(typeof window.HRST==="undefined")return"null";if(typeof window.HRST.article==="undefined")return"null";return window.HRST.article.template},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"HRST_article_template",collection:"Page",
source:"Manage",priv:"false"},{id:"55204"})},55204)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var cookie=Bootstrapper.Cookies.get("location_data");if(!cookie)return"n/a";var obj=JSON.parse(cookie);return obj.country_code},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"Fastly location_data Country Code",collection:"Page",
source:"Manage",priv:"false"},{id:"56304"})},56304)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){if(window.GDPR)return"true";return"false"},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"isGDPR",collection:"Page",source:"Manage",priv:"false"},{id:"60964"})},60964)},-1,-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(function(d){if(typeof HRST==="undefined")return;window.gptLayer=window.gptLayer||{};HRST.ab=HRST.ab||{};Bootstrapper.getValue=Bootstrapper.getValue||function(key,source,fallback){var parts=key.split(".");key=parts.shift();fallback=typeof fallback!=="undefined"?fallback:false;if(!source||!source.hasOwnProperty(key))return fallback;return parts.length?this.getValue(parts.join("."),
source[key],fallback):source[key]};function getCookie(name){var nameEQ=name+"\x3d",ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)===" ")c=c.substring(1,c.length);if(c.indexOf(nameEQ)===0){var result=c.substring(nameEQ.length,c.length);return result}}return""}function isSponsored(){if(Bootstrapper.getValue("article.sponsor",HRST,"")!==""){if(Bootstrapper.getValue("article.sponsor.name",HRST,"")!==""){if(Bootstrapper.getValue("article.sponsor.expirationDate",
HRST,"")!==""){var expDate=Bootstrapper.getValue("article.sponsor.expirationDate",HRST,"").split("-");var year=parseInt(expDate[2],10),month=parseInt(expDate[0],10)-1,day=parseInt(expDate[1],10)+1;expDate=(new Date(year,month,day)).getTime();if(expDate<Date.now())return false}return true}if(Bootstrapper.getValue("article.sponsor.program",HRST,"")==="None"||Bootstrapper.getValue("article.sponsor.program",HRST,"")==="")return false}return false}if(isSponsored())gptLayer.isSponsored=true;try{var utmCampaignCookie=
"";var utmCookie=getCookie("gpt_utm");if(utmCookie){var utmObj=JSON.parse(utmCookie);if(utmObj.hasOwnProperty("campaign"))utmCampaignCookie=utmObj.campaign}if(Bootstrapper.getParam("utm_campaign").match(/^arb|^mgu|^dda/i)||/^arb|^mgu|^dda/i.test(utmCampaignCookie)){HRST.isMgu=true;HRST.isARB=true}}catch(e){}})(document)},4142967,314123,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.MD5=function(r,modify){if(modify===undefined)modify="";if(r===undefined)r=Math.random()*1E10+"||"+window.location.href+"||"+(new Date).getTime()+"||"+modify;function n(r,n){return r<<n|r>>>32-n}function t(r,n){var t,o,e,u,f;return e=2147483648&r,u=2147483648&n,t=1073741824&r,o=1073741824&n,f=(1073741823&r)+(1073741823&n),t&o?2147483648^f^e^u:t|o?1073741824&
f?3221225472^f^e^u:1073741824^f^e^u:f^e^u}function o(r,n,t){return r&n|~r&t}function e(r,n,t){return r&t|n&~t}function u(r,n,t){return r^n^t}function f(r,n,t){return n^(r|~t)}function i(r,e,u,f,i,a,c){return r=t(r,t(t(o(e,u,f),i),c)),t(n(r,a),e)}function a(r,o,u,f,i,a,c){return r=t(r,t(t(e(o,u,f),i),c)),t(n(r,a),o)}function c(r,o,e,f,i,a,c){return r=t(r,t(t(u(o,e,f),i),c)),t(n(r,a),o)}function C(r,o,e,u,i,a,c){return r=t(r,t(t(f(o,e,u),i),c)),t(n(r,a),o)}function g(r){for(var n,t=r.length,o=t+8,e=
(o-o%64)/64,u=16*(e+1),f=Array(u-1),i=0,a=0;t>a;)n=(a-a%4)/4,i=a%4*8,f[n]=f[n]|r.charCodeAt(a)<<i,a++;return n=(a-a%4)/4,i=a%4*8,f[n]=f[n]|128<<i,f[u-2]=t<<3,f[u-1]=t>>>29,f}function h(r){var n,t,o="",e="";for(t=0;3>=t;t++)n=r>>>8*t&255,e="0"+n.toString(16),o+=e.substr(e.length-2,2);return o}function d(r){r=r.replace(/\r\n/g,"\n");for(var n="",t=0;t<r.length;t++){var o=r.charCodeAt(t);128>o?n+=String.fromCharCode(o):o>127&&2048>o?(n+=String.fromCharCode(o>>6|192),n+=String.fromCharCode(63&o|128)):
(n+=String.fromCharCode(o>>12|224),n+=String.fromCharCode(o>>6&63|128),n+=String.fromCharCode(63&o|128))}return n}var v,S,m,l,s,A,p,y,b,w=Array(),B=7,D=12,L=17,M=22,j=5,k=9,q=14,x=20,z=4,E=11,F=16,G=23,H=6,I=10,J=15,K=21;for(r=d(r),w=g(r),A=1732584193,p=4023233417,y=2562383102,b=271733878,v=0;v<w.length;v+=16)S=A,m=p,l=y,s=b,A=i(A,p,y,b,w[v+0],B,3614090360),b=i(b,A,p,y,w[v+1],D,3905402710),y=i(y,b,A,p,w[v+2],L,606105819),p=i(p,y,b,A,w[v+3],M,3250441966),A=i(A,p,y,b,w[v+4],B,4118548399),b=i(b,A,p,
y,w[v+5],D,1200080426),y=i(y,b,A,p,w[v+6],L,2821735955),p=i(p,y,b,A,w[v+7],M,4249261313),A=i(A,p,y,b,w[v+8],B,1770035416),b=i(b,A,p,y,w[v+9],D,2336552879),y=i(y,b,A,p,w[v+10],L,4294925233),p=i(p,y,b,A,w[v+11],M,2304563134),A=i(A,p,y,b,w[v+12],B,1804603682),b=i(b,A,p,y,w[v+13],D,4254626195),y=i(y,b,A,p,w[v+14],L,2792965006),p=i(p,y,b,A,w[v+15],M,1236535329),A=a(A,p,y,b,w[v+1],j,4129170786),b=a(b,A,p,y,w[v+6],k,3225465664),y=a(y,b,A,p,w[v+11],q,643717713),p=a(p,y,b,A,w[v+0],x,3921069994),A=a(A,p,y,
b,w[v+5],j,3593408605),b=a(b,A,p,y,w[v+10],k,38016083),y=a(y,b,A,p,w[v+15],q,3634488961),p=a(p,y,b,A,w[v+4],x,3889429448),A=a(A,p,y,b,w[v+9],j,568446438),b=a(b,A,p,y,w[v+14],k,3275163606),y=a(y,b,A,p,w[v+3],q,4107603335),p=a(p,y,b,A,w[v+8],x,1163531501),A=a(A,p,y,b,w[v+13],j,2850285829),b=a(b,A,p,y,w[v+2],k,4243563512),y=a(y,b,A,p,w[v+7],q,1735328473),p=a(p,y,b,A,w[v+12],x,2368359562),A=c(A,p,y,b,w[v+5],z,4294588738),b=c(b,A,p,y,w[v+8],E,2272392833),y=c(y,b,A,p,w[v+11],F,1839030562),p=c(p,y,b,A,w[v+
14],G,4259657740),A=c(A,p,y,b,w[v+1],z,2763975236),b=c(b,A,p,y,w[v+4],E,1272893353),y=c(y,b,A,p,w[v+7],F,4139469664),p=c(p,y,b,A,w[v+10],G,3200236656),A=c(A,p,y,b,w[v+13],z,681279174),b=c(b,A,p,y,w[v+0],E,3936430074),y=c(y,b,A,p,w[v+3],F,3572445317),p=c(p,y,b,A,w[v+6],G,76029189),A=c(A,p,y,b,w[v+9],z,3654602809),b=c(b,A,p,y,w[v+12],E,3873151461),y=c(y,b,A,p,w[v+15],F,530742520),p=c(p,y,b,A,w[v+2],G,3299628645),A=C(A,p,y,b,w[v+0],H,4096336452),b=C(b,A,p,y,w[v+7],I,1126891415),y=C(y,b,A,p,w[v+14],J,
2878612391),p=C(p,y,b,A,w[v+5],K,4237533241),A=C(A,p,y,b,w[v+12],H,1700485571),b=C(b,A,p,y,w[v+3],I,2399980690),y=C(y,b,A,p,w[v+10],J,4293915773),p=C(p,y,b,A,w[v+1],K,2240044497),A=C(A,p,y,b,w[v+8],H,1873313359),b=C(b,A,p,y,w[v+15],I,4264355552),y=C(y,b,A,p,w[v+6],J,2734768916),p=C(p,y,b,A,w[v+13],K,1309151649),A=C(A,p,y,b,w[v+4],H,4149444226),b=C(b,A,p,y,w[v+11],I,3174756917),y=C(y,b,A,p,w[v+2],J,718787259),p=C(p,y,b,A,w[v+9],K,3951481745),A=t(A,S),p=t(p,m),y=t(y,l),b=t(b,s);var N=h(A)+h(p)+h(y)+
h(b);return N.toLowerCase()};try{window.Bootstrapper.mdHash=Bootstrapper.MD5()}catch(e){console.warn("Error Generating Unique Hash")}try{window.Bootstrapper.mdHash=typeof juiceMdHash==="undefined"?Bootstrapper.MD5():juiceMdHash;if(!/^(autos|mag|mos\-video|riddler)/.test(Bootstrapper.ensightenOptions.publishPath)){window.Bootstrapper.mdHashArray=[window.Bootstrapper.mdHash];for(var i=0;i<50;i++)window.Bootstrapper.mdHashArray.push(Bootstrapper.MD5(undefined,i))}}catch(e){console.warn("Error Generating Unique Hash")}},
3498804,374590,24);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;window.HRST=window.HRST||{};let tcfQueue=[];function checkVendorConsent(vendorConsents,vendorId,callback,init=true){if(vendorConsents[vendorId]===true&&!window.CMP_GPP_OPTOUT&&!window.CMP_GPC_SET){gptLayer.log("checkVendorConsent","vendor consent",vendorConsents[vendorId]);return callback()}if(init)Bootstrapper.Events.listen(window,"cmp.consent.change",()=>{checkVendorConsent(vendorConsents,
vendorId,callback,false);return false},{once:true});return false}function checkTCFApi(vendorId,callback){const tcfCallback=(tcData,success)=>{if(success&&(tcData.eventStatus==="tcloaded"||tcData.eventStatus==="useractioncomplete")){const vendorConsents=tcData.vendor&&tcData.vendor.consents?tcData.vendor.consents:{};window.__tcfapi("removeEventListener",2,()=>{},tcData.listenerId);if(vendorConsents)checkVendorConsent(vendorConsents,vendorId,callback)}};window.__tcfapi("ping",2,()=>{window.__tcfapi("addEventListener",
2,tcfCallback)})}function waitForTCF(){if(typeof window.__tcfapi!=="undefined"){if(tcfQueue.length){tcfQueue.forEach(args=>{if(Array.isArray(args))checkTCFApi(...args)});tcfQueue=[]}return}setTimeout(waitForTCF,100)}window.getTCFConsent=window.getTCFConsent||function(type,id,tag,init=true){const cmpGpcSet=Bootstrapper.hasGPCSet();const cmpGppOptOut=Bootstrapper.hasGppOptOut();const notGDPROrOptedOut=!window.GDPR&&!cmpGppOptOut&&!cmpGpcSet;switch(type){case "category":try{if(notGDPROrOptedOut||window.GDPR_CONSENT_GROUPS.indexOf(id)>
-1){gptLayer.log("getTCFConsent",`category '${id}' consent`,true);if(tag)tag();return true}if(init)Bootstrapper.Events.listen(window,"cmp.consent.change",()=>{window.getTCFConsent(type,id,tag,false)},{once:true});break}catch(e){return false}break;case "vendor":if(notGDPROrOptedOut)return tag();if(typeof window.__tcfapi==="undefined")tcfQueue.push([id,tag]);else checkTCFApi(id,tag);return true;default:return false}return false};var euSite=/mag-(es|it|nl|uk)/.test(Bootstrapper.ensightenOptions.publishPath);
if(window.GDPR||euSite)waitForTCF();window.Bootstrapper=window.Bootstrapper||{};Bootstrapper.isNextFRE=!!window.__FRE;Bootstrapper.isLegacy=!!window.CURRENT_SITE;const windowLocationSearch=()=>window.location.search;Bootstrapper.getParam=function(name,fallback=""){try{const url=new URL(windowLocationSearch());return url.searchParams.get(name)?url.searchParams.get(name):fallback}catch(e){const finder=new RegExp(`[&?]${name}=?([^&]*)?`);const value=finder.exec(windowLocationSearch());if(value===null)return fallback;
return value[1]===undefined?true:value[1]}};Bootstrapper.getValue=function getValue(key,obj,def,p,undef){key=key&&key.split?key.split("."):[key];for(p=0;p<key.length;p+=1)obj=obj?obj[key[p]]:undef;return obj===undef||obj===""?def:obj};Bootstrapper.Cookies=function(){return{domain:function(){return document.domain}()||location.hostname,get:function(a,c){for(var b=document.cookie.split(";"),d=0;d<b.length;d++){var e=b[d].replace(/^\s+/,"");const [key,...value]=e.split("\x3d");const joinedValue=value.join("\x3d");
if(key===a)return c?joinedValue:decodeURIComponent(joinedValue)}return""},set:function(a,c,b){document.cookie=a+"\x3d"+encodeURIComponent(c)+(b?";expires\x3d"+b:"")+";path\x3d/;domain\x3d"+this.domain;return this.get(a)==c},test:function(a){return this.get(a)?!0:!1}}}();Bootstrapper.Events=function(){return{fire:function(element,eventName,data){var event=new CustomEvent(eventName,{detail:data});element.dispatchEvent(event)},listen:function(element,eventNames,func){var events=eventNames.split(" ");
for(var i=0;i<events.length;i++)element.addEventListener(events[i],func,false)}}}();Bootstrapper.getExtraParams=function(){var gdpr=Bootstrapper.getValue("GDPR",window,false)?"true":"false";var selfHosted="on";var template=Bootstrapper.getValue("HRST.article.template",window,"");var obj={"gdpr":gdpr,"selfhostedads":selfHosted,"template":template};var site=window.__SITE;if(site){obj.brand=site.brand;obj.locale=site.locale}return obj};Bootstrapper.hasGppOptOut=()=>{const optOut=!!window.CMP_GPP_OPTOUT;
if(optOut)return true;const hdmCmpCookie=Bootstrapper.Cookies.get("hdm_cmp");const hdmCmp=hdmCmpCookie?JSON.parse(hdmCmpCookie):"";if(hdmCmp)return hdmCmp&&hdmCmp.gpp&&hdmCmp.gpp.optOut!==undefined?hdmCmp.gpp.optOut:false;else return false};Bootstrapper.hasGPCSet=()=>{const gpcValue=!!(navigator&&navigator.globalPrivacyControl);return gpcValue};Bootstrapper.getCountry=function(){const d=Bootstrapper.Cookies.get("location_data");if(d)try{return JSON.parse(d).country_code}catch(e){return false}return false}},
4019830,454406,24);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();